# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b19a197df5be2f16e8abdb291a5e4240d0b9f458edbf5744f0d3a2f8d86264667f92cb16439bb4345949793dc6683fd8b5ae8550298a5b77cfa05b750bfe080

test:
  secret_key_base: f1491f69baf24989518851e320efbf38cfa26ab19816736197fa9442f53d40f8176c79fd6369bdc86d433d5364f4cc9b4d2db853ee14bc60a325ed29e534b162

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
